# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
inhibit_all_warnings!
# use_frameworks!

workspace 'MS13HUD'

project './MS13HUD.xcodeproj'
target :MS13HUD do
  pod 'JPush', '~> 3.0.7'
  pod 'Masonry'
end

target :MS13HUD_iOS do
    pod 'JPush', '~> 3.0.7'
    pod 'Masonry'
end


